# Site settings
author: Clay Stewart
title: Life
header-img: img/home-bg.png
email: c.stewart89@gmail.com
copyright_name: Clay Stewart
description: > # this means to ignore newlines until "baseurl:"
  My Coding Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  CuetheGreat

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
